解决生成视频报错的语法问题，当前不能成功生成视频，报错如下： [WinError -2147221008] 尚未调用 CoInitialize。 Can not load UIAutomationCore.dll. 1, You may need to install Windows Update KB971513 if your OS is Windows XP, see https://github.com/yinkaisheng/WindowsUpdateKB971513ForIUIAutomation 2, You need to use an UIAutomationInitializerInThread object if use uiautomation in a thread, see demos/uiautomation_in_thread.py 2025-09-02 22:40:39.411 | INFO | uvicorn.access | .venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py:476 | 127.0.0.1:52379 - "POST /openapi/v1/gen_video HTTP/1.1" 200 2025-09-02 22:40:39.411 | ERROR | uvicorn.error | .venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py:414 | Exception in ASGI application   + Exception Group Traceback (most recent call last):   |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_utils.py", line 77, in collapse_excgroups   |     yield   |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 183, in __call__   |     async with anyio.create_task_group() as task_group:   |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__   |     raise BaseExceptionGroup(   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)   +-+---------------- 1 ----------------     | Traceback (most recent call last):     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi     |     result = await app(  # type: ignore[func-returns-value]     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__     |     return await self.app(scope, receive, send)     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__     |     await super().__call__(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__     |     await self.middleware_stack(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__     |     raise exc     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__     |     await self.app(scope, receive, _send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 182, in __call__     |     with recv_stream, send_stream, collapse_excgroups():     |   File "C:\Program Files\Python\Python311\Lib\contextlib.py", line 158, in __exit__     |     self.gen.throw(typ, value, traceback)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_utils.py", line 83, in collapse_excgroups     |     raise exc     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 184, in __call__     |     response = await self.dispatch_func(request, call_next)     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\src\middlewares\prepare.py", line 14, in prepare_middleware     |     response = await call_next(request)     |                ^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next     |     raise app_exc     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 144, in coro     |     await self.app(scope, receive_or_disconnect, send_no_error)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app     |     raise exc     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app     |     await app(scope, receive, sender)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 716, in __call__     |     await self.middleware_stack(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 736, in app     |     await route.handle(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 290, in handle     |     await self.app(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 78, in app     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app     |     raise exc     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app     |     await app(scope, receive, sender)     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 75, in app     |     response = await f(request)     |                ^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\routing.py", line 302, in app     |     raw_response = await run_endpoint_function(     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\routing.py", line 215, in run_endpoint_function     |     return await run_in_threadpool(dependant.call, **values)     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\concurrency.py", line 38, in run_in_threadpool     |     return await anyio.to_thread.run_sync(func)     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync     |     return await get_async_backend().run_sync_in_worker_thread(     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2476, in run_sync_in_worker_thread     |     return await future     |            ^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run     |     result = context.run(func, *args)     |              ^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\src\router\v1.py", line 65, in gen_video     |     draft_url, message = service.gen_video(     |                          ^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\src\service\gen_video.py", line 28, in gen_video     |     ctrl = draft.JianyingController()     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\src\pyJianYingDraft\jianying_controller.py", line 64, in __init__     |     self.get_window()     |   File "C:\workspace\code\capcut-mate\src\pyJianYingDraft\jianying_controller.py", line 209, in get_window     |     if not self.app.Exists(0):     |            ^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 7132, in Exists     |     control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 10613, in FindControl     |     control = GetRootControl()     |               ^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 10379, in GetRootControl     |     control = Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.GetRootElement())     |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 57, in instance     |     cls._instance = cls()     |                     ^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 76, in __init__     |     raise ex     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 65, in __init__     |     self.IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}", interface=self.UIAutomationCore.IUIAutomation)     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\comtypes\client\_create.py", line 99, in CreateObject     |     obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     |   File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\comtypes\_post_coinit\misc.py", line 140, in CoCreateInstance     |     _CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p))     |   File "_ctypes/callproc.c", line 1000, in GetResult     | OSError: [WinError -2147221008] 尚未调用 CoInitialize。     +------------------------------------
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Program Files\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_utils.py", line 83, in collapse_excgroups
    raise exc
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\src\middlewares\prepare.py", line 14, in prepare_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\fastapi\routing.py", line 215, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\starlette\concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\src\router\v1.py", line 65, in gen_video
    draft_url, message = service.gen_video(
                         ^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\src\service\gen_video.py", line 28, in gen_video
    ctrl = draft.JianyingController()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\src\pyJianYingDraft\jianying_controller.py", line 64, in __init__
    self.get_window()
  File "C:\workspace\code\capcut-mate\src\pyJianYingDraft\jianying_controller.py", line 209, in get_window
    if not self.app.Exists(0):
           ^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 7132, in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 10613, in FindControl
    control = GetRootControl()
              ^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 10379, in GetRootControl
    control = Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.GetRootElement())
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 57, in instance
    cls._instance = cls()
                    ^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 76, in __init__
    raise ex
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\uiautomation\uiautomation.py", line 65, in __init__
    self.IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}", interface=self.UIAutomationCore.IUIAutomation)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\comtypes\client\_create.py", line 99, in CreateObject
    obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\code\capcut-mate\.venv\Lib\site-packages\comtypes\_post_coinit\misc.py", line 140, in CoCreateInstance
    _CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p))
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2147221008] 尚未调用 CoInitialize。